export const skills = [
    "Vanilla JavaScript",
    "BEM Standards",
    "HTML",
    "Encryption (bcrypt)",
    "Server Side Rendering (Next.js)",
    "Web Design (Figma)",
    "Dynamic Rendering",
    "Fetching JSON",
    "Browser Storage",
    "API Keys & UUID",
    "API Routing (Express/Next/Rails)",
    "CRUD + PostgreSQL",
    "Serverless (Lambda/API GW/RDS)",
    "DOM Manipulation",
    "Real-Time (SWR/WebRTC)",
    "CSV Cleaning (TS/Python)",
    "TDD / Jest",
    "Dagster Pipelines",
    "DBT Transformations",
    "DBT Macros & Tests",
    "Sisense Dashboards",
    "Debugging",
    "Data Modeling",
    "React State/Lifecycle",
    "Git/GitHub",
    "Jira",
    "Modular Programming",
  ];
  